#ifndef ALLOC_SETTINGS_H
#define ALLOC_SETTINGS_H

#define BACKWARDS_EXPLORATION_LIMIT 0
#define BUCKET_SIZE_GROWTH_FACTOR (1.25)
#define MIN_ALLOCATION_SIZE 16
#define NUM_BUCKETS 256
#define NUM_BUCKETS_FEW_BUCKET_MODE 16

#endif
