#ifndef ALLOC_SETTINGS_H
#define ALLOC_SETTINGS_H

#define MIN_ALLOCATION_SIZE 64
#define ALLOCATION_ALIGN 64
#define BUCKET_SIZE_GROWTH_FACTOR (1.5)
#define BUCKET_SIZE_GROWTH_FACTOR_FEW_BUCKET_MODE (1.5*1.5)
#define NUM_BUCKETS 256
#define NUM_BUCKETS_FEW_BUCKET_MODE 16

#endif
